-- ============================================================
-- CLINIC MANAGEMENT SYSTEM - POSTGRESQL DDL
-- ============================================================
CREATE TABLE address
    (
     patient_patient_id BIGINT  NOT NULL ,
     city              VARCHAR (100)  NOT NULL ,
     street            VARCHAR (100)  NOT NULL ,
     house_no           VARCHAR (10)  NOT NULL ,
     apartment_no       VARCHAR (10)
    )
;

ALTER TABLE address
    ADD CONSTRAINT address_pk PRIMARY KEY ( patient_patient_id ) ;

CREATE TABLE doctor
    (
     license_no    VARCHAR (7)  NOT NULL ,
     staff_user_id BIGINT  NOT NULL
    )
;

ALTER TABLE doctor
    ADD CONSTRAINT doctor_pk PRIMARY KEY ( staff_user_id ) ;

ALTER TABLE doctor
    ADD CONSTRAINT doctor_license_no_un UNIQUE ( license_no ) ;

CREATE TABLE exam_dict
    (
     exam_code VARCHAR (20)  NOT NULL ,
     exam_type VARCHAR (1)  NOT NULL ,
     exam_name VARCHAR (255)  NOT NULL
    )
;

ALTER TABLE exam_dict
    ADD
    CHECK (exam_type IN ('L', 'P'))
;

ALTER TABLE exam_dict
    ADD CONSTRAINT exam_dict_PK PRIMARY KEY ( exam_code ) ;

CREATE TABLE lab_exam
    (
     lab_exam_id               BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
     visit_visit_id           BIGINT  NOT NULL ,
     exam_dict_exam_code       VARCHAR (20)  NOT NULL ,
     doctor_notes             TEXT ,
     order_date               TIMESTAMP  NOT NULL ,
     result                  TEXT ,
     execution_cancel_date   TIMESTAMP ,
     manager_notes            TEXT ,
     approval_rejection_date TIMESTAMP ,
     status                  VARCHAR (50) DEFAULT 'Ordered'  NOT NULL ,
     lab_technician_user_id    BIGINT ,
     lab_manager_user_id       BIGINT
    )
;

ALTER TABLE lab_exam
    ADD
    CHECK (status IN ('Completed', 'Ordered', 'Rejected', 'Validated'))
;

ALTER TABLE lab_exam
    ADD CONSTRAINT lab_exam_pk PRIMARY KEY ( lab_exam_id ) ;

CREATE TABLE lab_manager
    (
     staff_user_id BIGINT  NOT NULL
    )
;

ALTER TABLE lab_manager
    ADD CONSTRAINT lab_manager_pk PRIMARY KEY ( staff_user_id ) ;

CREATE TABLE lab_technician
    (
     staff_user_id BIGINT  NOT NULL
    )
;

ALTER TABLE lab_technician
    ADD CONSTRAINT lab_technician_pk PRIMARY KEY ( staff_user_id ) ;

CREATE TABLE patient
    (
     patient_id        BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
     first_name        VARCHAR (100)  NOT NULL ,
     last_name         VARCHAR (100)  NOT NULL ,
     social_security_no VARCHAR (11)  NOT NULL ,
     date_of_birth      DATE  NOT NULL ,
     email            VARCHAR (100) ,
     phone_number      VARCHAR (15)  NOT NULL
    )
;

ALTER TABLE patient
    ADD CONSTRAINT patient_pk PRIMARY KEY ( patient_id ) ;

ALTER TABLE patient
    ADD CONSTRAINT patient_social_security_no_un UNIQUE ( social_security_no ) ;

CREATE TABLE physical_exam
    (
     physical_exam_id    BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
     visit_visit_id     BIGINT  NOT NULL ,
     exam_dict_exam_code VARCHAR (20)  NOT NULL ,
     result            TEXT
    )
;

ALTER TABLE physical_exam
    ADD CONSTRAINT physical_exam_pk PRIMARY KEY ( physical_exam_id ) ;

CREATE TABLE receptionist
    (
     staff_user_id BIGINT  NOT NULL
    )
;

ALTER TABLE receptionist
    ADD CONSTRAINT receptionist_pk PRIMARY KEY ( staff_user_id ) ;

CREATE TABLE staff
    (
     user_id    BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
     first_name VARCHAR (100)  NOT NULL ,
     last_name  VARCHAR (100)  NOT NULL ,
     login     VARCHAR (100)  NOT NULL ,
     password  VARCHAR (100)  NOT NULL ,
     is_active  VARCHAR (1) DEFAULT 'Y'  NOT NULL ,
     user_type  VARCHAR (50)  NOT NULL
    )
;

ALTER TABLE staff
    ADD
    CHECK (is_active IN ('N', 'Y'))
;

ALTER TABLE staff
    ADD
    CHECK (user_type IN ('Administrator', 'Doctor', 'LabManager', 'LabTechnician', 'Receptionist'))
;

ALTER TABLE staff
    ADD CONSTRAINT staff_pk PRIMARY KEY ( user_id ) ;

ALTER TABLE staff
    ADD CONSTRAINT staff_login_un UNIQUE ( login ) ;

CREATE TABLE visit
    (
     visit_id                BIGINT  GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
     patient_patient_id      BIGINT  NOT NULL ,
     description            TEXT  NOT NULL ,
     diagnosis              TEXT ,
     status                 VARCHAR (50) DEFAULT 'Registered'  NOT NULL ,
     registration_date       TIMESTAMP  NOT NULL ,
     completion_cancel_date TIMESTAMP ,
     doctor_user_id          BIGINT  NOT NULL ,
     receptionist_user_id    BIGINT  NOT NULL ,
     appointment_date        TIMESTAMP  NOT NULL
    )
;

ALTER TABLE visit
    ADD
    CHECK (status IN ('Cancelled', 'Finished', 'Registered'))
;

ALTER TABLE visit
    ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id ) ;

ALTER TABLE address
    ADD CONSTRAINT address_patient_fk FOREIGN KEY
    (
     patient_patient_id
    )
    REFERENCES patient
    (
     patient_id
    )
    ON DELETE CASCADE
;

ALTER TABLE doctor
    ADD CONSTRAINT doctor_staff_fk FOREIGN KEY
    (
     staff_user_id
    )
    REFERENCES staff
    (
     user_id
    )
    ON DELETE CASCADE
;

ALTER TABLE lab_exam
    ADD CONSTRAINT lab_exam_exam_dict_fk FOREIGN KEY
    (
     exam_dict_exam_code
    )
    REFERENCES exam_dict
    (
     exam_code
    )
;

ALTER TABLE lab_exam
    ADD CONSTRAINT lab_exam_lab_manager_fk FOREIGN KEY
    (
     lab_manager_user_id
    )
    REFERENCES lab_manager
    (
     staff_user_id
    )
;

ALTER TABLE lab_exam
    ADD CONSTRAINT lab_exam_lab_technician_fk FOREIGN KEY
    (
     lab_technician_user_id
    )
    REFERENCES lab_technician
    (
     staff_user_id
    )
;

ALTER TABLE lab_exam
    ADD CONSTRAINT lab_exam_visit_fk FOREIGN KEY
    (
     visit_visit_id
    )
    REFERENCES visit
    (
     visit_id
    )
    ON DELETE CASCADE
;

ALTER TABLE lab_manager
    ADD CONSTRAINT lab_manager_staff_fk FOREIGN KEY
    (
     staff_user_id
    )
    REFERENCES staff
    (
     user_id
    )
    ON DELETE CASCADE
;

ALTER TABLE lab_technician
    ADD CONSTRAINT lab_technician_staff_fk FOREIGN KEY
    (
     staff_user_id
    )
    REFERENCES staff
    (
     user_id
    )
    ON DELETE CASCADE
;

ALTER TABLE physical_exam
    ADD CONSTRAINT physical_exam_exam_dict_fk FOREIGN KEY
    (
     exam_dict_exam_code
    )
    REFERENCES exam_dict
    (
     exam_code
    )
;

ALTER TABLE physical_exam
    ADD CONSTRAINT physical_exam_visit_fk FOREIGN KEY
    (
     visit_visit_id
    )
    REFERENCES visit
    (
     visit_id
    )
    ON DELETE CASCADE
;

ALTER TABLE receptionist
    ADD CONSTRAINT receptionist_staff_fk FOREIGN KEY
    (
     staff_user_id
    )
    REFERENCES staff
    (
     user_id
    )
    ON DELETE CASCADE
;

ALTER TABLE visit
    ADD CONSTRAINT visit_doctor_fk FOREIGN KEY
    (
     doctor_user_id
    )
    REFERENCES doctor
    (
     staff_user_id
    )
    ON DELETE CASCADE
;

ALTER TABLE visit
    ADD CONSTRAINT visit_patient_fk FOREIGN KEY
    (
     patient_patient_id
    )
    REFERENCES patient
    (
     patient_id
    )
    ON DELETE CASCADE
;

ALTER TABLE visit
    ADD CONSTRAINT visit_receptionist_fk FOREIGN KEY
    (
     receptionist_user_id
    )
    REFERENCES receptionist
    (
     staff_user_id
    )
    ON DELETE CASCADE
;

-- --- INITIAL DICTIONARY DATA (exam_dict) ---

-- Laboratory Exams (Type 'L')
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('C55', 'L', 'Morphology (Full Blood Count)');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('L43', 'L', 'Glucose Level (Serum)');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('A01', 'L', 'Urinalysis (General)');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('O17', 'L', 'Lipid Profile (CHOL, LDL, HDL, TG)');

-- Physical Exams (Type 'P')
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('89.142', 'P', 'Holter EEG');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('89.383', 'P', 'Spirometry Test');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('81.92', 'P', 'Joint or Ligament Injection');
INSERT INTO exam_dict (exam_code, exam_type, exam_name) VALUES ('95.1901', 'P', 'Visual Acuity Test');


-- ============================================================
-- INITIAL TEST DATA (SEED DATA)
-- ============================================================

-- 1. STAFF & USERS (Passwords are 'pass123' for simplicity)
INSERT INTO staff (first_name, last_name, login, password, is_active, user_type)
VALUES ('System', 'Admin', 'admin', 'pass123', 'Y', 'Administrator');

INSERT INTO staff (first_name, last_name, login, password, is_active, user_type)
VALUES ('Gregory', 'House', 'drhouse', 'pass123', 'Y', 'Doctor');

INSERT INTO staff (first_name, last_name, login, password, is_active, user_type)
VALUES ('Pam', 'Beesly', 'pam_reception', 'pass123', 'Y', 'Receptionist');

INSERT INTO staff (first_name, last_name, login, password, is_active, user_type)
VALUES ('Dexter', 'Morgan', 'dexter_lab', 'pass123', 'Y', 'LabTechnician');

INSERT INTO staff (first_name, last_name, login, password, is_active, user_type)
VALUES ('Walter', 'White', 'heisenberg_mgr', 'pass123', 'Y', 'LabManager');

-- 2. STAFF ROLES (Linking staff to specific roles)
INSERT INTO doctor (license_no, staff_user_id)
SELECT 'MD12345', user_id FROM staff WHERE login = 'drhouse';

INSERT INTO receptionist (staff_user_id)
SELECT user_id FROM staff WHERE login = 'pam_reception';

INSERT INTO lab_technician (staff_user_id)
SELECT user_id FROM staff WHERE login = 'dexter_lab';

INSERT INTO lab_manager (staff_user_id)
SELECT user_id FROM staff WHERE login = 'heisenberg_mgr';

-- 3. PATIENTS
INSERT INTO patient (first_name, last_name, social_security_no, date_of_birth, email, phone_number)
VALUES ('John', 'Doe', '90010112345', '1990-01-01', 'john.doe@email.com', '+48555100200');

INSERT INTO patient (first_name, last_name, social_security_no, date_of_birth, email, phone_number)
VALUES ('Jane', 'Smith', '85051254321', '1985-05-12', 'jane.smith@email.com', '+48555300400');

INSERT INTO patient (first_name, last_name, social_security_no, date_of_birth, email, phone_number)
VALUES ('Will', 'Hunting', '95122598765', '1995-12-25', 'will.smart@email.com', '+48555900800');

-- 4. ADDRESSES (Linked to Patients 1, 2, 3)
INSERT INTO address (patient_patient_id, city, street, house_no, apartment_no)
VALUES (1, 'New York', 'Wall Street', '12', '4B');

INSERT INTO address (patient_patient_id, city, street, house_no, apartment_no)
VALUES (2, 'Scranton', 'Electric Ave', '172', NULL);

INSERT INTO address (patient_patient_id, city, street, house_no, apartment_no)
VALUES (3, 'Boston', 'Southie St', '9', '1');

-- 5. VISITS
-- Completed Visit
INSERT INTO visit (patient_patient_id, description, diagnosis, status, registration_date, completion_cancel_date, doctor_user_id, receptionist_user_id, appointment_date)
VALUES (1, 'Routine checkup and blood pressure issues.', 'Mild hypertension.', 'Finished', '2026-03-01 09:00:00', '2026-03-01 10:30:00', 2, 3, '2026-03-01 10:00:00');

-- Upcoming Registered Visit
INSERT INTO visit (patient_patient_id, description, diagnosis, status, registration_date, completion_cancel_date, doctor_user_id, receptionist_user_id, appointment_date)
VALUES (2, 'Severe headache and blurred vision.', NULL, 'Registered', '2026-04-01 14:00:00', NULL, 2, 3, '2026-04-10 11:30:00');

-- 6. SAMPLE LAB EXAMS
INSERT INTO lab_exam (visit_visit_id, exam_dict_exam_code, doctor_notes, order_date, status)
VALUES (1, 'C55', 'Please check hemoglobin levels.', '2026-03-01 09:15:00', 'Completed');

-- 7. SAMPLE PHYSICAL EXAMS
INSERT INTO physical_exam (visit_visit_id, exam_dict_exam_code, result)
VALUES (1, '95.1901', 'Vision 20/20 in both eyes.');